export const TOGGLE_ACTIVE = "TOGGLE_ACTIVE";
export const TOGGLE_INACTIVE = "TOGGLE_INACTIVE";
export const SORT_ASCENDING = "SORT_ASCENDING";
export const SORT_DESCENDING = "SORT_DESCENDING";
export const SEARCH_USER_NAME = "SEARCH_USER_NAME";
